name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.Project-exam.pem}}
        SSH_HOST: ${{ secrets.ec2-44-203-122-163.compute-1.amazonaws.com}}
        SSH_USERNAME: ${{ secrets.ubuntu }}
        PROJECT_PATH: ${{ secrets./home/ubuntu/var/www/html }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST 'bash -s' << 'EOF'
        cd $PROJECT_PATH
        git pull origin main
        npm install
        npm run build
        EOF